services:
  - type: web
    name: jetlag-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - fromGroup: env-clr5vhqdrqts73fmvkr0
    routes:
      - type: rewrite
        source: /*
        destination: /
    healthCheckPath: /api
    autoDeploy: true 