export const CIRCADIAN_CONSTANTS = {
  MAX_SHIFT_PER_DAY: 60,
  MIN_SLEEP_DURATION: 420,
  MAX_SLEEP_DURATION: 540,
  LIGHT_EXPOSURE_DURATION: 3,
  MIN_LIGHT_DURATION: 0.5,
  MAX_LIGHT_DURATION: 4,
  PHASE_SHIFT_RATE: 1.0,
  FATIGUE_HALF_LIFE: 24,
  OPTIMAL_LIGHT_ADVANCE_HOURS: 120,
  OPTIMAL_LIGHT_DELAY_HOURS: 120,
  MELATONIN_WINDOW: 0.5,
  CAFFEINE_CUTOFF: 6,
  AVERAGE_ADJUSTMENT_RATE: 1,
  MAX_LIGHT_INTENSITY: 10000,
  MELATONIN_BEFORE_BED: 60
};

export const LIGHT_EXPOSURE_ADJUSTMENT = {
  ADVANCE: {
    MAX_SHIFT: 1,
    OPTIMAL_WINDOW_START: 2,
    OPTIMAL_WINDOW_DURATION: 2
  },
  DELAY: {
    MAX_SHIFT: 1.5,
    OPTIMAL_WINDOW_START: -3,
    OPTIMAL_WINDOW_DURATION: 2
  }
};

export const MELATONIN_ADJUSTMENT = {
  ADVANCE: {
    DAILY_SHIFT: 1,
    OPTIMAL_WINDOW: -2
  },
  DELAY: {
    DAILY_SHIFT: 1.5,
    OPTIMAL_WINDOW: -2
  }
}; 